### PR TITLE
Small error on dev branch

### PR DESCRIPTION
**Pull request by corentinravoux**
The class SNIaGen was not calling the variable SNIA_M0 in one of its function.

### CODE REVIEW

**Comment by bastiencarreres** [comment]
@DamianoRosselli Is it a solved problem in your branch?

**Comment by corentinravoux** [comment]
Go to vacation !

**Comment by DamianoRosselli** [comment]
In my branch was fine because all the constants where in the file constant.py

Go to vacation !

**Comment by DamianoRosselli** [comment]
For the fix just doing:
self.SNIA_M0['jla']
should be fine

**Comment by bastiencarreres** [comment]
I generalize the code as:
```
elif self._params['M0'].lower() in self.SNIA_M0:
            return ut.scale_M0_cosmology(self.cosmology.h,
                                         self.SNIA_M0[self._params['M0'].lower()], 
                                         cst.h_article[self._params['M0'].lower()])
```

**Pull request merged**
